default_mode = "full"

[templates.motorola_xt2301_5_13_tp1a]
manufacturer = "Motorola"
brand = "motorola"
model = "XT2301-5"
device = "eqs"
product = "eqs_g"
name = "eqs"
marketname = "Motorola XT2301-5"
fingerprint = "motorola/eqs_g/eqs:13/TP1A.220226.025/68ZMN9:user/release-keys"
mode = "full"
author = "Telegram@SarhanHassan1"
