default_mode = "full"

[templates.motorola_xt2301_5_11_rr2a]
manufacturer = "Motorola"
brand = "motorola"
model = "XT2301-5"
device = "eqs"
product = "eqs_g"
name = "eqs"
marketname = "Motorola XT2301-5"
fingerprint = "motorola/eqs_g/eqs:11/RR2A.241103.382/9A1BUG:user/release-keys"
packages = [ "com.logistics.rider.talabat", "com.logistics.rider.hungerstation" ]
mode = "full"
author = "Telegram@SarhanHassan1"
